### ISSUE TITLE
Cannot get property 'apiLevel' on null object

### ISSUE THREAD

**Issue by zhangyunhua** [OkBuilds/OkBuck#152] opened 2016-08-10 11:46 UTC
* What went wrong:
Execution failed for task ':okbuck'.
> Cannot get property 'apiLevel' on null object

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':okbuck'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NullPointerException: Cannot get property 'apiLevel' on null object
	at com.github.okbuilds.core.model.AndroidTarget.<init>(AndroidTarget.groovy:45)
	at com.github.okbuilds.core.model.AndroidLibTarget.<init>(AndroidLibTarget.groovy:13)
	at com.github.okbuilds.core.util.ProjectUtil$_getTargetForOutput_closure4.doCall(ProjectUtil.groovy:72)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
	at org.gradle.api.DomainObjectCollection$all$0.call(Unknown Source)
	at com.github.okbuilds.core.util.ProjectUtil.getTargetForOutput(ProjectUtil.groovy:67)
	at com.github.okbuilds.core.util.ProjectUtil$getTargetForOutput$1.call(Unknown Source)
	at com.github.okbuilds.core.model.Scope$_extractConfigurations_closure2$_closure3.doCall(Scope.groovy:61)
	at com.github.okbuilds.core.model.Scope$_extractConfigurations_closure2.doCall(Scope.groovy:54)
	at com.github.okbuilds.core.model.Scope.extractConfigurations(Scope.groovy:50)
	at com.github.okbuilds.core.model.Scope.<init>(Scope.groovy:40)
	at com.github.okbuilds.core.model.Scope.<init>(Scope.groovy)
	at com.github.okbuilds.core.model.AndroidTarget.getMain(AndroidTarget.groovy:61)
	at com.github.okbuilds.core.model.JavaTarget.resolve(JavaTarget.groovy:76)
	at com.github.okbuilds.core.model.JavaTarget$resolve.call(Unknown Source)
	at com.github.okbuilds.okbuck.generator.BuckFileGenerator$_resolve_closure5.doCall(BuckFileGenerator.groovy:52)
	at com.github.okbuilds.okbuck.generator.BuckFileGenerator.resolve(BuckFileGenerator.groovy:51)
	at com.github.okbuilds.okbuck.generator.BuckFileGenerator$_generate_closure1.doCall(BuckFileGenerator.groovy:29)
	at com.github.okbuilds.okbuck.generator.BuckFileGenerator.generate(BuckFileGenerator.groovy:28)
	at com.github.okbuilds.okbuck.generator.BuckFileGenerator$generate.call(Unknown Source)
	at com.github.okbuilds.okbuck.OkBuckGradlePlugin.generate(OkBuckGradlePlugin.groovy:97)
	at com.github.okbuilds.okbuck.OkBuckGradlePlugin$_apply_closure3.doCall(OkBuckGradlePlugin.groovy:51)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more

BUILD FAILED

**Comment by Piasy** [comment] 2016-08-10 12:16
Do you specify `targetSdkVersion` and `minSdkVersion` in your build.gradle? If not, please set them.

**Comment by NickPan365** [comment] 2016-08-22 03:11
I got the same problem, and i checked all the module project 's build.gradle files ， I'm sure minSdkVersion，compileSdkVersion，targetSdkVersion，buildToolsVersion were all specified.


:okbuck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':okbuck'.
> Cannot get property 'apiLevel' on null object

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':okbuck'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NullPointerException: Cannot get property 'apiLevel' on null object
	at com.github.okbuilds.core.model.AndroidTarget.<init>(AndroidTarget.groovy:46)
	at com.github.okbuilds.core.model.AndroidLibTarget.<init>(AndroidLibTarget.groovy:13)
	at com.github.okbuilds.core.util.ProjectUtil$_getTargetForOutput_closure4.doCall(ProjectUtil.groovy:72)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
	at org.gradle.api.DomainObjectCollection$all$2.call(Unknown Source)
	at com.github.okbuilds.core.util.ProjectUtil.getTargetForOutput(ProjectUtil.groovy:67)
	at com.github.okbuilds.core.util.ProjectUtil$getTargetForOutput$1.call(Unknown Source)
	at com.github.okbuilds.core.model.Scope$_extractConfigurations_closure2$_closure3.doCall(Scope.groovy:61)
	at com.github.okbuilds.core.model.Scope$_extractConfigurations_closure2.doCall(Scope.groovy:54)
	at com.github.okbuilds.core.model.Scope.extractConfigurations(Scope.groovy:50)
	at com.github.okbuilds.core.model.Scope.<init>(Scope.groovy:40)
	at com.github.okbuilds.core.model.Scope.<init>(Scope.groovy:31)
	at com.github.okbuilds.core.model.JavaTarget.getApt(JavaTarget.groovy:31)
	at com.github.okbuilds.core.model.JavaTarget.resolve(JavaTarget.groovy:75)
	at com.github.okbuilds.core.model.JavaTarget$resolve.call(Unknown Source)
	at com.github.okbuilds.okbuck.generator.BuckFileGenerator$_resolve_closure5.doCall(BuckFileGenerator.groovy:52)
	at com.github.okbuilds.okbuck.generator.BuckFileGenerator.resolve(BuckFileGenerator.groovy:51)
	at com.github.okbuilds.okbuck.generator.BuckFileGenerator$_generate_closure1.doCall(BuckFileGenerator.groovy:29)
	at com.github.okbuilds.okbuck.generator.BuckFileGenerator.generate(BuckFileGenerator.groovy:28)
	at com.github.okbuilds.okbuck.generator.BuckFileGenerator$generate.call(Unknown Source)
	at com.github.okbuilds.okbuck.OkBuckGradlePlugin.generate(OkBuckGradlePlugin.groovy:96)
	at com.github.okbuilds.okbuck.OkBuckGradlePlugin$_apply_closure2.doCall(OkBuckGradlePlugin.groovy:50)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more

**Comment by kageiit** [comment] 2016-09-25 06:57
Latest installation instructions in README

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.github.okbuilds:okbuild-gradle-plugin:0.5.3'
    }
}

apply plugin: 'com.github.okbuilds.okbuck-gradle-plugin'
```

Please re-open if it is happening in latest version. Closing for now

**Closed by kageiit** 2016-09-25 06:57 UTC

**Comment by Piasy** [comment] 2016-09-25 06:59
@kageiit This issue did happen, I think we should check the `apiLevel` in advance, so we could give more useful information about how developer could correct the error.

**Comment by kageiit** [comment] 2016-09-25 07:08
Thanks @Piasy for clarification.

@zhangyunhua @NickPan365 to mitigate these sort of issues, I would recommend you follow the structure of this project https://github.com/kageiit/android-studio-gradle-test and have a top level configuration file to make sure you do not miss setting any important values
