### ISSUE TITLE
Buck randomly throws BUILD FAILED errors

### ISSUE THREAD

**Issue by ragunathjawahar** [OkBuilds/OkBuck#142] opened 2016-08-02 13:13 UTC
The project compiles fine after initial configuration, however if a `buck clean` command is invoked, subsequent calls to `build targets` or `build install [target]` throws the following error.

1. `buck install appDebug`
````
BUILD FAILED: //app:src_debug: parameter 'manifest': no such file or directory 'app/build/okbuck/debug/AndroidManifest.xml'
````

2. `buck install appDebug`
````
BUILD FAILED: //app:manifest_release: parameter 'skeleton': no such file or directory 'app/build/okbuck/release/AndroidManifest.xml'
````

3. `buck build appDebug`
````
BUILD FAILED: //app:manifest_release: parameter 'skeleton': no such file or directory 'app/build/okbuck/release/AndroidManifest.xml'
````

4. `buck targets`
````
BUILD FAILED: //app:manifest_release: parameter 'skeleton': no such file or directory 'app/build/okbuck/release/AndroidManifest.xml'
````

**Comment by kageiit** [comment] 2016-08-05 07:16
Can you try with the latest version? We fixed an issue with old BUCK files not being cleaned up when gradle modules moved around

**Comment by ragunathjawahar** [comment] 2016-08-05 11:07
I am using `0.3.1`

**Comment by kageiit** [comment] 2016-08-07 01:27
Unable to reproduce this on the sample project included in this repo. Can you upload a sample project or make a branch on this repo that reproduces your issue?

**Comment by ragunathjawahar** [comment] 2016-08-10 04:57
@kageiit Sure, will do.

**Comment by kageiit** [comment] 2016-09-25 06:57
Latest installation instructions in README

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.github.okbuilds:okbuild-gradle-plugin:0.5.3'
    }
}

apply plugin: 'com.github.okbuilds.okbuck-gradle-plugin'
```

Use the buck wrapper. Please re-open if it is happening in latest version. Closing for now

**Closed by kageiit** 2016-09-25 06:57 UTC
Labels: bug

**Comment by 2BAB** [comment] 2016-09-28 02:08
BUILD FAILED: //app:manifest_releaseChangeEnv: parameter 'skeleton': no such file or directory 'app/build/okbuck/releaseChangeEnv/AndroidManifest.xml'

0.6.0, happen again? I have
